name: AWS OIDC Test II
on:
  workflow_dispatch: # Allows you to run this manually from the "Actions" tab

permissions:
  id-token: write # Required for requesting the JWT
  contents: read  # Required for actions/checkout

jobs:
  test-ecr-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::391119427586:role/GitHub_Actions_Access # Replace with your Role ARN
          aws-region: us-east-2 # Replace with your preferred region

      - name: Create Test ECR Repo
        run: |
          aws ecr create-repository --repository-name oidc-test-repoii

      # - name: List Repos (Verification)
      #   run: |
      #     aws ecr describe-repositories --repository-names oidc-test-repo

      - name: Count ECR Repos
        run: |
          COUNT=$(aws ecr describe-repositories --query 'length(repositories)' --output text)
          echo "Total ECR repositories: $COUNT"
      # - name: Delete Test ECR Repo
      #   if: always() # Ensures cleanup even if the creation or list steps fail
      #   run: |
      #     aws ecr delete-repository --repository-name oidc-test-repo --force
